######################################################################
# Automatically generated by qmake (3.0) ?? 6? 7 17:41:09 2016
######################################################################

TEMPLATE = app
TARGET = Qvlc

# install
target.path = /home/pi
INSTALLS += target


INCLUDEPATH += .

QT += widgets

LIBS += -lvlc

# Input
HEADERS += vlc_on_qt.h
SOURCES += main.cpp vlc_on_qt.cpp



